# Generated by Django 3.1.12 on 2025-03-09 14:40

import Nested_app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(max_length=50)),
                ('UserRegistration', djongo.models.fields.EmbeddedField(model_container=Nested_app.models.UserRegistration, null=True)),
                ('LocationDetails', djongo.models.fields.EmbeddedField(model_container=Nested_app.models.LocationDetails, null=True)),
                ('UserProfileDetails', djongo.models.fields.EmbeddedField(model_container=Nested_app.models.UserProfileDetails, null=True)),
            ],
        ),
    ]
